"""
image.py — Image and InferenceResult ORM models.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import JSON, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


class Image(Base):
    """
    Represents one uploaded image from an edge device.

    status lifecycle:
      pending → processing → completed
                           → failed
    """

    __tablename__ = "images"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id"), nullable=False, index=True
    )
    device_id: Mapped[str] = mapped_column(String(128), nullable=False)
    filename: Mapped[str] = mapped_column(String(255), nullable=False)

    # MinIO object paths
    raw_storage_path: Mapped[str] = mapped_column(String(512), nullable=False)

    # ISO-8601 datetime reported by the edge device
    captured_at: Mapped[str] = mapped_column(String(32), nullable=False)
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now
    )

    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending"
    )
    # Named image_metadata, not metadata — that name is reserved by SQLAlchemy's Declarative API.
    image_metadata: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # Relationship to AI results
    inference_result: Mapped["InferenceResult | None"] = relationship(
        "InferenceResult", back_populates="image", uselist=False
    )

    def __repr__(self) -> str:
        return f"<Image id={self.id} status={self.status} device={self.device_id}>"


class InferenceResult(Base):
    """
    Stores the AI pipeline output for a single image.
    Created by the Celery inference worker after processing.
    """

    __tablename__ = "inference_results"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    image_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("images.id"), nullable=False, unique=True, index=True
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id"), nullable=False, index=True
    )

    # Path to the annotated image in MinIO
    annotated_image_path: Mapped[str | None] = mapped_column(String(512), nullable=True)

    # YOLOv8 detections: list of {class_name, class_id, confidence, bbox: [x1,y1,x2,y2]}
    yolo_detections: Mapped[list | None] = mapped_column(JSON, nullable=True)

    # Mask R-CNN results: list of {class_name, class_id, confidence, mask_area, bbox}
    segmentation_results: Mapped[list | None] = mapped_column(JSON, nullable=True)

    # Per-component detected counts: {"column": 4, "beam": 7, ...}
    component_counts: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # Overall progress 0.0 – 100.0
    progress_percentage: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Per-component progress breakdown
    component_progress: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # MWPI score (0.0–1.0) and which milestone classes triggered it
    mwpi_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    detected_classes: Mapped[list | None] = mapped_column(JSON, nullable=True)

    # Per-class completion ratios for this frame: raw (pre-smoothing, feeds the
    # median filter of later frames) and latched (what actually scored MWPI).
    class_ratios_raw: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    class_ratios: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # Plain-English progress summary generated by Claude. Nullable — pipeline
    # still saves the result even if explanation generation fails.
    explanation: Mapped[str | None] = mapped_column(Text, nullable=True)

    processed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now
    )
    processing_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    image: Mapped["Image"] = relationship("Image", back_populates="inference_result")

    def __repr__(self) -> str:
        return (
            f"<InferenceResult image={self.image_id} "
            f"progress={self.progress_percentage:.1f}%>"
        )
