"""
worker.py — Worker Activity Monitoring ORM models.

Three models:
  WorkShift             — contractor-configured working hours + expected headcount
  WorkerPresenceReading — one person-count snapshot from a presence_check image
  WorkerAlert           — fired when Late Start or Low Presence thresholds are crossed
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


class WorkShift(Base):
    """
    Defines contracted working hours for a project.
    One active shift per project at a time (active=True).
    Times stored as "HH:MM" strings in local site time (no tz conversion —
    the contractor enters local time and the Pi uploads with local timestamps).
    """

    __tablename__ = "work_shifts"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    contracted_start: Mapped[str] = mapped_column(String(5), nullable=False)   # "08:00"
    contracted_end: Mapped[str] = mapped_column(String(5), nullable=False)     # "17:00"
    expected_headcount: Mapped[int] = mapped_column(Integer, nullable=False, default=5)
    # Grace period in minutes before a LATE_START alert fires
    late_start_grace_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=30)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    def __repr__(self) -> str:
        return (
            f"<WorkShift project={self.project_id} "
            f"{self.contracted_start}–{self.contracted_end} "
            f"headcount={self.expected_headcount} active={self.active}>"
        )


class WorkerPresenceReading(Base):
    """
    One headcount snapshot — created each time a presence_check image is processed.
    worker_count is the number of persons detected by YOLO (person class).
    """

    __tablename__ = "worker_presence_readings"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    shift_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("work_shifts.id", ondelete="SET NULL"),
        nullable=True,
    )
    image_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("images.id", ondelete="SET NULL"),
        nullable=True,
    )
    worker_count: Mapped[int] = mapped_column(Integer, nullable=False)
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    def __repr__(self) -> str:
        return (
            f"<WorkerPresenceReading project={self.project_id} "
            f"count={self.worker_count} at={self.captured_at}>"
        )


class WorkerAlert(Base):
    """
    An alert generated by the worker monitoring system.

    alert_type values:
      LATE_START        — no workers detected after grace period past contracted_start
      LOW_PRESENCE      — worker count < expected_headcount // 2 during work hours
      EARLY_DEPARTURE   — worker count drops to 0 before contracted_end

    severity: "critical" or "warning"
    """

    __tablename__ = "worker_alerts"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    project_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    shift_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("work_shifts.id", ondelete="SET NULL"),
        nullable=True,
    )
    alert_type: Mapped[str] = mapped_column(String(32), nullable=False)
    severity: Mapped[str] = mapped_column(String(16), nullable=False)   # critical | warning
    message: Mapped[str] = mapped_column(Text, nullable=False)
    worker_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    triggered_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    resolved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    def __repr__(self) -> str:
        return (
            f"<WorkerAlert project={self.project_id} "
            f"type={self.alert_type} severity={self.severity} resolved={self.resolved}>"
        )
